// ideology_summaries.js (Updated for 34 ideologies)

const ideologySummaries = {
    // --- I. STATISM (Dominant C) ---
    "Totalitarianism / Absolutism": "Welcome to paradise, where The State is your loving parent, your stern teacher, your only friend, and the omnipresent interior decorator of your soul. Every thought is a public service, every joy is state-sanctioned, and the Department of Approved Fun has a surprisingly long waiting list. Remember, Big Brother isn't just watching you; he's also deeply invested in your choice of breakfast cereal – as long as it's the State-Approved Brand Oats of Righteousness. Conformity isn't just encouraged; it's the national pastime, and the re-education centers have excellent (if somewhat repetitive) team-building exercises. Your unique individuality will be carefully cataloged and then gently sanded down for the greater good.",
    "State Communism / Marxism-Leninism": "Fear not, comrades, for The Party, guided by the infallible science of Marxism-Leninism (and a few helpful purges), has a meticulously detailed Five-Year Plan for your eternal happiness! All property is owned by the people (which means The State, which means The Party, which means a few guys at the top, who are definitely *not* forming a new ruling class, nope). True equality is achieved when everyone has equally little, except for Party officials who are, naturally, 'more equal.' Shortages are merely tests of revolutionary zeal, and the gulags offer excellent opportunities for 'productive reflection' on any lingering bourgeois tendencies (or just for anyone who looked at the General Secretary funny).",
    "Nationalist Collectivism (Strasserite/NazBol Type)": "Forget that bourgeois class struggle or decadent international finance! The REAL revolution is national (and probably racial)! We'll have totalitarian state control, a 'socialist' economy for the chosen people, and crush all enemies, foreign and domestic (especially those tricky capitalists *and* those other kinds of communists who don't get the 'national' part). It's like regular communism, but with more eagles, mystical runes, less sophisticated economic theory, and an even shorter fuse. All power to the national-socialist-Bolshevik-whatever-we-call-it-this-week revolution!",
    "Nationalist Corporatism (Fascist/Falangist Type)": "The Nation is an organic spiritual entity, not just a boring contract! Society will be harmoniously organized into state-controlled syndicates (corporations) where worker and employer 'collaborate' for national glory (spoiler: the workers do most of the 'collaborating' by doing what they're told). Tradition, Faith (the approved version, naturally), and a strong, charismatic Leader will forge national greatness. Dissent is just a lack of national spirit, easily corrected with some castor oil or a firm chat with the Blackshirts/Blueshirts/WhicheverColorShirtsAreInVogue.",
    "Paternalistic/Traditionalist Statism": "Now, now, don't you worry your pretty little head about all those complicated modern problems, dear. The State, much like a slightly overbearing but ultimately well-meaning grandparent who still thinks a good leeching cures all, will handle everything with time-tested wisdom and a firm hand. Just follow the nice traditions, respect your elders (especially the ones in power making all the rules for your benefit), and everything will be orderly and predictable. Innovation is fine, as long as it was approved three generations ago. For your own good, of course. And no, you can't have the car keys.",
    "Authoritarian Capitalism (Fascist Economic Type)": "National glory! Economic might! A strong leader to tell us what to think! We're all about efficiency and order here, where the trains run on time (even if they're heading to a 'special' work camp) and private enterprise thrives (as long as it's buddies with the State and contributes generously to the Party's 'special projects' fund). Individual rights are a quaint suggestion, easily overridden by national destiny, a really cool uniform, or just a Tuesday. Dissent? That's just a sign you haven't fully appreciated the majesty of our five-color charts outlining total national synergy.",
    "Statism (General Authoritarian)": "Look, someone needs to be in charge, okay? And that someone is probably The State, because frankly, most of you can't be trusted to tie your own shoes without creating societal chaos. We'll make the rules, you'll follow them, and things will be orderly. The specifics of 'how' or 'why' are less important than the comforting certainty that there *are* rules and someone is enforcing them with a suitably stern expression. Freedom is nice in theory, but have you tried predictable conformity? It's very calming.",

    // --- II. LIBERTARIAN SOCIALISM / SOCIAL ANARCHISM (Dominant M, Low C) ---
    "Anarcho-Communism": "No gods, no masters, no money, and definitely no private ownership of that slightly dented spork you found! In our glorious, stateless, classless utopia, everything from the artisanal bread to the means of production (and your extensive collection of protest zines) is held joyfully in common. Decisions are made by vibrant, consensus-based assemblies that *definitely* won't drag on for seven hours discussing the optimal placement of the communal compost heap. Expect thriving community gardens, a flourishing local craft scene powered by mutual aid, and the gentle, collective re-education of anyone who asks 'But who will build the roads?' The answer is: 'We all will, comrade, between our interpretive dance workshops and our advanced Kropotkin reading group!' (Council Communists might add something about factory committees here, but details, details).",
    "Left Communism (General)": "While those sell-out Leninists were busy building 'state capitalism' and those other 'socialists' were pathetically begging for reforms, we, the true Left Communists, have kept the revolutionary flame pure! (The flame is currently tended by about twelve people, globally, who mostly communicate through sharply worded critiques of each other's interpretations of Marx's early writings). We await the spontaneous, international proletarian uprising, uncorrupted by parties, unions, or any form of organization that might actually achieve something pragmatic. Anyone not agreeing with our precise, 700-page platform is, of course, an objective agent of bourgeois reaction. The world revolution is imminent, just as soon as the working class reads our latest journal.",
    "Guild Socialism": "Finally, a solution that's not rapacious capitalism OR soul-crushing state bureaucracy: it's... medieval craft guilds, but with Wi-Fi! Each industry will be its own cozy, self-governing Guild, democratically deciding everything from widget quotas to the official Guild Anthem. The State? Oh, it'll be a quaint little coordinating body, mostly organizing the annual All-Guilds Bake-Off and publishing strongly worded suggestions when the Shoemakers Guild inevitably declares a crippling tariff on the output of the Button-Makers Guild. Expect a vibrant economy of artisanal everything, assuming the Guild of Essential Infrastructure Maintenance ever actually agrees on a five-year plan that doesn't involve just more meetings.",
    "Democratic Confederalism / Libertarian Municipalism": "Forget nations, the real power lies with your neighborhood assembly and the freely federated councils! We're building a stateless, direct democracy from the grassroots up, inspired by Bookchin and the revolutionary spirit of Rojava. Expect intense local meetings, a deep commitment to social ecology (your compost better be sorted!), gender equality as a non-negotiable, and a socialized economy built on co-ops and communal resources. Participation isn't just encouraged; it's how we make sure the lights stay on and the communal library is well-stocked with radical theory.",
    "Anarcho-Syndicalism / Collectivist Anarchism": "Workers of the world, unite, seize the means of production, and then run everything yourselves through your glorious, federated unions and worker collectives! One Big General Strike, and capitalism crumbles, replaced by a sensible, stateless society where every industry is a self-managed democracy. Managers? Bureaucrats? Relics of a bygone era! Direct action gets the goods, and your shop steward is now also your political representative and possibly your kid's soccer coach. Solidarity forever, and pass the collectively bargained kombucha.",
    "De Leonism": "Behold the two-fisted approach to utopia! With one mighty industrial union fist, we seize all industry! With the other, equally mighty socialist political party fist, we... also seize all industry, but, like, politically! Then these two perfectly harmonious fists merge to form the all-powerful Industrial Union Government, where your shop steward is also your senator, and national policy is decided at the biennial conference of the Amalgamated Sprocket Makers and Associated Trades. Don't worry about those pesky details like 'who represents the consumers?' or 'what if the Party and the Unions disagree?' – it's all flawlessly outlined in Daniel De Leon's pamphlets, which you'll have plenty of time to read while waiting for your union-approved toaster.",
    "Social Anarchism (General/Eclectic)": "Down with hierarchy! Up with freedom, equality, and solidarity! We're smashing the state and capitalism, and then... well, we'll build something beautiful and cooperative based on voluntary association and mutual aid. The exact blueprint is a bit fluid – maybe some communes, maybe some worker co-ops, definitely fewer bosses and more community gardens. The point is, we'll figure it out together, without anyone telling us what to do. As long as it's anti-authoritarian, it's probably good!",

    // --- III. PROPERTARIANISM / INDIVIDUALIST LIBERTARIANISM (Dominant P, Low C) ---
    "Voluntaryism": "If you didn't sign a notarized contract agreeing to it, it's basically a crime against humanity – especially if it's the State doing it! In our utopia, every single service, from your artisanal coffee delivery to your Private Dispute Resolution Officer (Bronze Tier Subscription: resolves disputes via strongly worded email), is 100% voluntary. Roads? Pothole-filling is a passion project funded by GoFundMe. National Defense? A patchwork of competing mercenary groups offering 'Aggression Deterrence Packages.' If your neighbor's house is on fire and they didn't subscribe to McFirefighters Inc., well, that's their sovereign choice to become a barbecue. Freedom!",
    "Anarcho-Capitalism": "The Non-Aggression Principle is our one true god, and every human interaction is a voluntary contract, preferably notarized and enforced by your chosen Private Defense Agency™. Roads? Private. Courts? Private. Your personal army of battle-drones to protect your authentically scarce Beanie Baby collection? Absolutely private! If you can't afford your subscription to McJustice™ or the local warlord's 'protection' services, well, that's just the glorious free market performing its natural selection duties. Taxation is theft, the state is a gang, and your only duty is to get rich and leave everyone else alone (unless they're trespassing).",
    "Geolibertarianism": "It's so simple, it's genius! Landlords are history's greatest villains, so we'll just have one landlord: Everyone! We'll slap a Single Tax on the 'unimproved value' of land (good luck agreeing on that valuation, especially for your prime beachfront mudflat), and all other pesky taxes vanish! This magical LVT will either fund a tiny, perfect government OR shower us all with a citizen's dividend, instantly solving poverty and probably climate change too. Beyond that, it's a glorious free-for-all of capitalist enterprise on land you technically only rent from... well, yourself and everyone else. Don't think too hard about it; just enjoy your utopia (minus the land speculation).",
    "Radical Propertarianism / Hoppeanism (Economic Aspect)": "Private property rights are absolute, sacrosanct, and the only basis for a civilized society. And by 'civilized,' we mean one composed of self-owning individuals in covenanted communities who can, by right of property, physically remove anyone who doesn't meet their exacting standards of decorum, genetic purity, or economic productivity. The state is an illegitimate protection racket, but a system of purely private law and private defense will naturally lead to an orderly, hierarchical, and culturally homogenous (because we said so) utopia. It's not fascism, it's just... *efficiently enforced private preference*.",
    "Minarchism / Night-Watchman State": "The government should do exactly three things: protect your property from foreign invaders with a sensible army, protect your property from domestic ne'er-do-wells with a lean police force, and enforce your contracts with an efficient court system. Anything more is creeping tyranny and an egregious waste of my (minimal) tax dollars. Social welfare? That's what private charity and 'personal responsibility' are for. Just give me my guns, my gold, and get off my damn (privately owned and meticulously maintained) lawn.",
    "Agorism / Counter-Economics": "Starve the vile State, feed the vibrant Grey Market! Every untaxed, unregulated transaction you make – from bartering bitcoins for backyard moonshine to running an unlicensed therapy llama service – is a revolutionary act of defiance. We're building the Second Realm of freedom right under the noses of the statist pigs, one black market deal and encrypted message at a time. Why overthrow the government when you can just make it irrelevant by peacefully (and profitably) ignoring it into oblivion?",
    "Conservative Libertarianism": "Sure, free markets and individual liberty are foundational, absolutely! But let's not get carried away with all that 'smash the state' nonsense or those weirdos with the llamas. We need a robust government to enforce contracts, protect our borders, maintain law and order (especially against those with fewer assets), and perhaps gently encourage traditional moral values that keep society from becoming a total Burning Man festival. It's like libertarianism, but with more police, a stronger military, and a healthy suspicion of anyone with blue hair or too many feelings.",
    "Libertarianism (Right-Libertarian / Propertarian General)": "Don't tread on me, my property, or my God-given right to make questionable financial decisions! Individual liberty, free markets, and a government so small you can barely see it are the sacred trinity. Regulations are shackles, taxes are plunder, and personal responsibility is king. If everyone just minded their own business and pursued their own profit, the invisible hand would give us all a high-five (and a healthy ROI).",

    // --- IV. AUTHORITARIAN SOCIALISM / STATE COLLECTIVISM (High C & High M, Low P) ---
    "State Socialism (Centralized Planning Focus)": "The State, in its infinite wisdom (and with the help of some very large spreadsheets and an army of apparatchiks), will provide for all your needs... eventually. Our meticulously crafted Five-Year Plan for Universal Happiness and Abundant Tractor Production is only slightly behind schedule due to unforeseen bourgeois wreckers. Innovation is... carefully managed to align with Plan objectives. Queues build character, and remember, your individual desires are secondary to the glorious collective output (as determined by us, for you).",
    "State Collectivism": "We're all in this glorious collective together... and The State will ensure our togetherness is properly organized and ideologically sound! Community spirit is mandatory, and your individual quirks are best channeled into activities that benefit the collective, as defined by the Ministry of Collective Benefit and Enthusiastic Conformity. Think mandatory group calisthenics followed by a rousing chorus of the National Community Anthem, twice daily.",
    "National Syndicalism (Non-Fascist)": "Forget messy class conflict! Society will be harmoniously organized into state-approved functional groups – guilds for the artisans, syndicates for the workers, associations for the professionals, all under the benevolent (and firm) guidance of The State. Everyone knows their place, cooperates for the national good, and private property exists to serve these productive, patriotic ends. It's like a well-oiled machine, where cogs don't question the engineer, especially if the engineer has a five-year plan and a large portrait.",
    "Authoritarian Socialism (General)": "Socialism is such a fantastic idea, it simply *must* be mandatory, and The State is just the entity to enforce that wonderful mandatoriness with sensible five-year plans and a firm but fair bureaucracy. We'll ensure equality, collective well-being, and the correct ideological outlook, even if it requires a bit of... firm persuasion and some re-education seminars. Dissent is just a sign you haven't fully grasped how great this all is for you and the collective.",

    // --- V. INDIVIDUALIST ANARCHISM (Low C; M & P both significant) ---
    "Mutualism": "Fair exchange is no robbery, but rent, interest, and profit derived from state-backed monopoly most certainly are! We advocate for a society of federated free individuals and associations, where workers receive the full product of their labor, land is held by occupancy and use, and credit is democratized through mutual banks (that definitely won't cause a run on the turnip reserves). It's free markets, yes, but free markets *without* capitalism's exploitative privileges, leading to widespread self-employment and cooperative prosperity. Property is liberty (when it's earned, not stolen via usury!).",
    "Free Market Anti-Capitalism": "The State is the chief villain, creating and protecting the monopolies (land, money, patents, tariffs) that allow capitalists to fleece the working person! Abolish these privileges, and a truly free market – a market of sovereign individuals contracting freely – will ensure labor is justly rewarded and exploitation withers. Natural law and individual conscience are paramount. Don't even *think* about initiating force against me or my justly acquired possessions; I've probably written a lengthy pamphlet on why that's illegitimate and will bore you to death with it.",
    "Communal Individualism / Egoism (Stirnerite, in voluntary association)": "My Will is my only law, and my Property is whatever I have the power to take and enjoy! Society, morality, rights? All 'spooks' in your head, designed to constrain ME, the Unique One. I'll form a 'Union of Egoists' with other Unique Ones if it pleases me and serves my interests (mostly getting more stuff or avoiding boredom), and dissolve it just as readily. Your 'common good' is not my concern, unless it happens to align with my self-enjoyment. Now, get out of my sunlight, unless you have something interesting to offer ME.",
    // Philosophical Anarchism removed from ideal points

    // --- VI. CLASSICAL LIBERALISM / CONSTITUTIONALISM (High C & High P, Low M) ---
    "Classical Liberalism (Lockean/Smithian)": "Life, liberty, and property – the holy trinity, secured by a limited government operating under the rule of law and with the consent of the governed (who are, ideally, property-owning, rational gentlemen like us). Free markets, individual rights, and a healthy dose of rational self-interest will lead to prosperity for all... or at least for those who are industrious and not unlucky. The 'invisible hand' will sort out the details, mostly. Just don't expect the government to coddle you or, heaven forbid, tax our wigs.",
    "Traditional Conservatism (Burkean)": "Hold on there, progressives with your fancy 'rights of man'! Change is perilous, tradition embodies accumulated wisdom (mostly ours), and established institutions (like monarchy and a sensible class structure) are the bedrock of a stable society. Order, hierarchy, piety, and a healthy skepticism of abstract utopian schemes (and overly enthusiastic Frenchmen) are essential. Society is an organic compact between the dead, the living, and the yet to be born, not a playground for radical experimentation. Prudence, darling, prudence!",
    "Constitutional Republicanism / Conservative Liberalism": "We need a well-ordered republic, governed by wise laws and virtuous (preferably property-owning) citizens, not the whims of a monarch or the passions of the mob. Individual rights are important, yes, but they must be balanced with civic duty, public order, and the preservation of our venerable institutions (and our powdered wigs). Limited, constitutional government is key, preferably run by the 'better sort' of people who understand such things and don't use too many exclamation marks.",
    "Liberalism (General Constitutional)": "Rights, reason, and a well-structured government that protects individual freedoms while ensuring a level playing field and public order. It's all about balance, really – a constitutional framework that allows for both liberty and responsible governance, ideally with lots of learned debate in well-appointed drawing rooms. Extremes are vulgar; sensible, incremental progress within established legal norms is the way. (Probably thinks John Stuart Mill had some good points, even if he was a bit radical on the ladies).",

    // --- VII. CENTRISM / MIXED ECONOMY IDEOLOGIES (C, M, & P all Moderate/Balanced) ---
    "Social Democracy": "Look, capitalism is a wild horse – powerful, sure, but it'll trample everyone if you don't tame it with a strong welfare state, robust unions, and a tax system that makes billionaires cry a little into their caviar. We're aiming for that cozy Scandinavian vibe: everyone gets healthcare, education, and a sensible Volvo. It's not revolution, it's just... making capitalism less of a soul-crushing nightmare for most people. Also, a balanced budget, mostly.",
    "Market-Oriented Liberalism / Third Way": "We're 'beyond left and right,' finding that 'radical center' where market dynamism meets social responsibility (and a focus group said this sounds great)! It's like social democracy, but with more buzzwords, a greater fondness for public-private partnerships, and a PowerPoint presentation explaining how 'flexicurity' and 'lifelong learning' will solve everything while we deregulate a bit. We're empowering individuals by making them more 'employable' in the ever-shifting global marketplace. Tony Blair and Bill Clinton would approve, probably over a low-fat latte.",
    "Technocratic / Managerial Liberalism": "Society is essentially a very complex engineering problem, best solved by highly educated experts armed with data, algorithms, and a calm, rational demeanor (and perhaps a slight god complex). If we just optimize the inputs, fine-tune the regulations, and apply evidence-based policies, we can manage our way to a more efficient and prosperous future. Politics and messy human emotions? Inefficient variables to be minimized. Trust the science (and the elite university graduates interpreting it for the government).",
    "Radical Centrism / Syncretic Politics": "Left wing, right wing... it's all part of the same tired, squawking bird! Why pick a side when you can cherry-pick the 'best ideas' from everywhere (or what sounds good this week), blend them into a pragmatic (if slightly incoherent) smoothie, and solve problems without all that ideological baggage? Accusations of having no core principles are just partisan noise from those who can't appreciate true intellectual flexibility (or a well-placed weather vane and a focus group).",
    "Social Liberalism / Progressive Liberalism": "Individual liberty is paramount, but let's be real, not everyone starts at the same place. True liberty requires a society that actively works to ensure fairness, equality of opportunity, and protection for the vulnerable (without, you know, too much actual wealth redistribution that might upset our donors). Markets are generally good, but they need a social conscience and a government willing to intervene with well-meaning (if sometimes complex and bureaucratic) programs to correct their failings, protect rights, and expand freedoms. It's about progress, but, you know, sensibly and inclusively, with lots of stakeholder consultations.",
    // Ordoliberalism was removed from ideal points.

    // --- VIII. DEMOCRATIC SOCIALISM (Distinct Broad Category) ---
    "Democratic Socialism": "Capitalism is fundamentally flawed, folks. We need to move beyond it, but, like, democratically, with votes and stuff, not necessarily storming the Winter Palace (though some historical LARPing is fine). Think worker co-ops, greatly expanded public ownership of key industries, decommodification of essentials, and a society run for people, not profit. It's like Social Democracy's cooler, more radical older sibling who actually read Marx and wants systemic change, not just better band-aids for capitalism.",

    // --- IX. ULTIMATE FALLBACK & BROAD CATEGORY SUMMARIES ---
    "Mixed / Eclectic Political Outlook": "You're a beautiful, chaotic enigma of political thought! A free-range thinker grazing across the ideological spectrum, or perhaps you just enjoy keeping everyone guessing (including yourself). You defy easy categorization, which is either a sign of profound intellectual independence or a desperate need for a more consistent worldview. Either way, you're probably interesting at dinner parties, assuming you can decide which one to attend.",
    "Statism": "In your view, The State is, or should be, a pretty big deal – a central organizing force, a powerful authority, or the primary problem-solver. The 'why' and 'how' might be a bit fuzzy, but more government, more rules, or more centralized power generally seems like the way to go. Details to be determined by the relevant Ministry (of Details).",
    "Libertarian Socialism / Social Anarchism": "Freedom AND equality, without the state (or capitalists) bossing everyone around – that's the dream! You're all about empowering people and communities from the bottom up, through voluntary cooperation, direct action, and mutual aid. The specifics might vary (cue sectarian infighting), but it definitely involves less hierarchy and more sharing (and probably a lot of meetings about sharing).",
    "Propertarianism / Individualist Libertarianism": "Your core belief: My life, my liberty, my property – keep your government hands and your collective paws off! Individual rights (especially the right to own ludicrous amounts of stuff), free markets, and minimal (if any) state interference are the paths to prosperity and freedom. What you do on your own (heavily fortified) property is your business. And yes, taxation is still theft.",
    "Authoritarian Socialism / State Collectivism": "You reckon socialism or collectivism is the way forward, and a strong, guiding (and probably rather bossy) State is necessary to make it happen properly and keep everyone on the correct ideological path. Individual desires might need to take a backseat to the collective good, as defined and managed from the top by people who know best (i.e., us). Don't worry, it's for your own good, comrade... or else.",
    "Individualist Anarchism": "No gods, no masters, and definitely no state telling me what to do! My individual sovereignty is paramount. Associations? Sure, if they're voluntary and benefit ME. Markets? Fine, as long as they're free of state coercion and monopoly. Just don't tread on ME, my unique and unrepeatable self. (Hair-splitting about property norms with other anarchists is a beloved pastime).",
    "Classical Liberalism / Constitutionalism": "You believe in a society grounded in individual rights (especially property), the rule of law (that we wrote), and a limited, constitutional government that protects those rights rather than infringes upon them (too much). Reason, order, and a framework for liberty are key, preventing tyranny from above or (shudder) chaos from below. A powdered wig is optional but encouraged.",
    "Centrism / Mixed Economy Ideologies": "Extremes? No, thank you! You're looking for a sensible balance, a middle way, a pragmatic blend of different approaches that hopefully won't make *too* many people angry. Whether it's market forces with a social safety net, or individual liberty with community responsibility, you're convinced the best answers lie somewhere in the reasonable, well-regulated, and probably slightly boring center."
};